fix: make actions file match latest build script
Due to GitHub restrictions, ZRAM and sched_ext integration is not available in GitHub Actions.

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -33,31 +33,26 @@ on:
         description: 'CPU codename'
         required: true
         default: 'waipio'
-      kernelsu_variant:
-        description: "KernelSU variant"
-        required: false
-        type: choice
-        options:
-          - Official
-          - KSUN
-          - MKSU
-          - RKSU
-          - SKSU
-        default: MKSU
-      kernelsu_manual_hooks:
-        description: 'Use manual hooks to integrate KernelSU'
-        required: false
+      sukisu_enable:
+        description: "Enable SukiSU-Ultra"
+        required: true
         type: boolean
+        default: true
+      kpm_enable:
+        description: "Enable KernelPatch module"
+        required: true
+        type: boolean
+        default: true
+      sukisu_manual_hooks:
+        description: 'Use manual hooks to integrate SukiSU-Ultra'
+        required: true
+        type: boolean
+        default: true
       susfs_enabled:
         description: 'Enable susfs'
         required: true
         type: boolean
         default: true
-      build_with_bazel:
-        description: 'Build with bazel'
-        required: false
-        type: boolean
-        default: false
 
 permissions: 
   contents: read
@@ -94,43 +89,45 @@ jobs:
         id: init_args
         run: |
           args=''
+          output_string=`echo '_${{ inputs.file }}' | sed -E 's/(_[a-z])?\.xml$//'`
+
           if [[ '${{ inputs.repo }}' ]]; then
             args+=" -r '${{ inputs.repo }}'"
           fi
 
-          if [[ '${{ inputs.kernelsu_variant }}' ]]; then
-            args+=" -k '${{ inputs.kernelsu_variant }}'"
+          if [[ '${{ inputs.sukisu_enable }}' == true ]]; then
+            args+=' -k'
+            output_string+='_SKSU'
 
-            if [[ '${{ inputs.susfs_enabled }}' == 'true' ]]; then
+            if [[ '${{ inputs.kpm_enable }}' == true ]]; then
+              args+=' -K'
+              output_string+='_KPM'
+            fi
+
+            if [[ '${{ inputs.susfs_enabled }}' == true ]]; then
               if [[ ! '${{ inputs.gki_abi }}' ]]; then
                 echo 'Error: GKI ABI is required when susfs is enabled.'
                 exit 1
               fi
 
               args+=" -g '${{ inputs.gki_abi }}'"
+              output_string+='_SUSFS'
             else
-              args+=" -s false"
+              args+=' -s false'
             fi
 
-            if [[ '${{ inputs.kernelsu_manual_hooks }}' == 'true' ]]; then
-              case '${{ inputs.kernelsu_variant }}-${{ inputs.susfs_enabled }}' in
-                KSUN-*|RKSU-*|SKSU-true)
-                  args+=" -m"
-                  ;;
-                *)
-                  echo 'Error: Manual hooks are only supported for KSUN, RKSU, and SKSU with susfs.'
-                  exit 1
-                  ;;
-              esac
-              args+=" -m"
+            if [[ '${{ inputs.sukisu_manual_hooks }}' == true ]]; then
+              if [[ '${{ inputs.susfs_enabled }}' == true ]]; then
+                args+=' -m'
+              else
+                echo 'Error: Manual hooks are only supported in SukiSU-Ultra with SUSFS.'
+                exit 1
+              fi
             fi
-          fi
-
-          if [[ '${{ inputs.build_with_bazel }}' == 'true' ]]; then
-            args+=" -z"
           fi
 
           echo "args=$args" >> $GITHUB_OUTPUT
+          echo "output_string=$output_string" >> $GITHUB_OUTPUT
 
       - name: Init
         run: |
@@ -154,19 +151,16 @@ jobs:
 
       - name: Make AnyKernel3
         run: |
-          cd workspace
-          git clone https://github.com/Kernel-SU/AnyKernel3 --depth=1
-          rm -rf ./AnyKernel3/.git
-          cp out/dist/Image ./AnyKernel3
+          ./scripts/make_ak3.sh
 
       - name: Upload AnyKernel3
         uses: actions/upload-artifact@v4
         with:
-          name: 'AnyKernel3_${{ inputs.kernelsu_variant }}${{ inputs.kernel_name }}.zip'
+          name: 'AnyKernel3${{ steps.init_args.outputs.output_string }}${{ inputs.kernel_name }}.zip'
           path: ./workspace/AnyKernel3/*
 
       - name: Upload kernel
         uses: actions/upload-artifact@v4
         with:
-          name: 'kernel-${{ inputs.kernelsu_variant }}${{ inputs.kernel_name }}'
+          name: 'Image${{ steps.init_args.outputs.output_string }}${{ inputs.kernel_name }}'
           path: ./workspace/out/dist/Image
